name: Build and deploy My Portfolio

on:
  push:
    branches: ["master"]

  workflow_dispatch:
env:
  APP_NAME: portfolio

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: prod

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Azure container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push the container image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ vars.REGISTRY_LOGIN_SERVER }}/${{ env.APP_NAME }}:latest
          file: ./Dockerfile

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: prod
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          creds: ${{secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.APP_NAME }}
          images: ${{ vars.REGISTRY_LOGIN_SERVER }}/${{ env.APP_NAME }}:latest
